// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int N = Integer.parseInt(args[0]);
		int greater= 0;
		int lower = 0;
		for (int i = 0; i < N; i++) {
			double random = Math.random();
			if (random > 0.5) {
				greater ++;
			}
			else {
				lower ++;
			}
		}
		System.out.println("> 0.5: " + greater + " times");
		System.out.println("<= 0.5: " + lower + " times");
		if (greater != 0 && lower != 0) {
			double ratio = (double) greater / lower;
			System.out.println("ratio: " + ratio);
		}
	}
}